version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'sunday'
      time: '12:34'
      timezone: 'Asia/Shanghai'
    labels:
      - 'dependencies'
    commit-message:
      prefix: 'chore'
      include: 'scope'
    ignore:
      - dependency-name: 'vue'
        update-types: ['version-update:semver-major']
